version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: gripinvest_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gripinvest
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
